### ISSUE TITLE
Add possibility to exclude endpoints you don't want send access token to

### ISSUE THREAD

**Issue by davidbilik** [AckeeCZ/ackroutine-adapter#32]

**Comment by johnondrej** [comment]
In my opinion, the best solution would be to make `OAuthManager` `open`, so that you can provide your own implementation of the Auth interceptor  (for adding `Authorization` header) in `provideAuthInterceptor()` function without having to implement the whole `AuthManager`. This will be a more general approach that will allow other modifications besides this use case.
